export const FETCH_TODOS = 'FETCH_TODOS'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SHOW_ERROR = 'HIDE_LOADER'
export const CLEAR_ERROR = 'CLEAR_ERROR'